<?php
return [
    'title' => 'Elevi',
    'single' => 'Elev',
    'model' => 'App\Elev',
    'columns' => [
        'id_specialitate'=> [
            'title' => 'Specialitate 1',
            'relationship' => 'specialitates',
            'select' => "(:table).denumire",
        ],
        'buget1',
        'contract1',
        'nota1',
        'media1',
        'limba1'=>[
            'title' => 'Limba 1',
            'relationship' => 'languages1',
            'select' => "(:table).language",
        ],
        'id_specialitate2' =>[
            'title' => 'Specialitate 2',
            'relationship' => 'specialitates2',
            'select' => "(:table).denumire",
        ],
        'buget2',
        'contract2',
        'nota2',
        'media2',
        'limba2'=>[
            'title' => 'Limba 2',
            'relationship' => 'languages2',
            'select' => "(:table).language",
        ],
        'id_specialitate3' => [
            'title' => 'Specialitate 3',
            'relationship' => 'specialitates3',
            'select' => "(:table).denumire",
        ],
        'buget3',
        'contract3',
        'nota3',
        'media3',
        'limba3'=>[
            'title' => 'Limba 3',
            'relationship' => 'languages3',
            'select' => "(:table).language",
        ],
        'nationality_id' => [
            'title' => 'Nationalitatea',
            'relationship' => 'Nationalitys',
            'select' => "(:table).nationality",
        ],

        'nume',
        'prenume',
        'patronimic',
        'email',
        'cod_personal',
        'numar_buletin',
        'oficiu',
        'an_abs',
        'acte',
        'sex',
        'datanasterii',
        'certificat_data_eliberarii',
        'buletin_data_eliberarii',
        'tat_nume',
        'tat_prenume',
        'mam_nume',
        'mam_prenume',
        'cetatanie',
        'seria_certificat',
        'seria_buletin',
        'adresa',
        'raion',
        'telefon',
        'telefon_mobil',
        'sat_oras',
        'inst_abs',
        'distinc_abs',
        'doc_seria',
        'limba_de_instruire'=>[
            'title' => 'Limba de instruire',
            'relationship' => 'languages3',
            'select' => "(:table).language",
        ],
        'limba_studiata'=>[
            'title' => 'Limba studiata',
            'relationship' => 'languages3',
            'select' => "(:table).language",
        ],
        'media_discipline',
        'media_exam',
        'gimnaziu',
        'livret_militar',
        'camin',
        'aloling',
        'cop_orfan',
        'cop_invalid',
        'cop_deficiente',
        'parinti_invalizi',
        'parinti_Cernobil',
        'mm_patru_copii',
        'raion_est',
        'cop_roman',
        'serv_milit',
        'ucrainean',
        'un_par_inv',
    ],
    'edit_fields' => [
        'admin' => [
            'nume' => 'text',
        ],
    ],
    'action_permissions'=> [
        'create' => function($model)
        {
            return false;
        }
    ],
];